### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by michael-hou** [saucelabs/sauce_ruby#169]
Was following this tutorial: https://ww.saucelabs.com/ruby
It went smooth until...

$ rake sauce:spec --trace 
(in c:/rspec/auto) 
*\* Invoke sauce:spec (first_time) 
*\* Execute sauce:spec 
3 processes for 3 specs, ~ 1 specs per process 
rake aborted! 
No such file or directory - SAUCE_PERFILE_BROWSERS='{"./spec/features/ramen_spec 
.rb":[{"os":"OS X 10.8","browser":"Safari","version":"6"}]}';export SAUCE_PERFIL 
E_BROWSERS;TEST_ENV_NUMBER=3;export TEST_ENV_NUMBER;PARALLEL_TEST_GROUPS=5;expor 
t PARALLEL_TEST_GROUPS;bundle exec rspec --color --tty spec/features/ramen_spec. 
rb 
c:/Ruby193/lib/ruby/gems/1.9.1/gems/parallel_tests-0.15.0/lib/parallel_tests/tes 
t/runner.rb:68:in `open' 
c:/Ruby193/lib/ruby/gems/1.9.1/gems/parallel_tests-0.15.0/lib/parallel_tests/tes 
t/runner.rb:68:in`execute_command_and_capture_output' 
c:/Ruby193/lib/ruby/gems/1.9.1/gems/parallel_tests-0.15.0/lib/parallel_tests/tes 
t/runner.rb:58:in `execute_command' 
c:/Ruby193/lib/ruby/gems/1.9.1/gems/sauce-3.0.6/lib/parallel_tests/saucerspec/ru 
nner.rb:16:in`run_tests' 
c:/Ruby193/lib/ruby/gems/1.9.1/gems/parallel_tests-0.15.0/lib/parallel_tests/cli 
.rb:53:in `run_tests' 
c:/Ruby193/lib/ruby/gems/1.9.1/gems/sauce-3.0.6/lib/parallel_tests/cli_patch.rb: 
14:in`block (2 levels) in run_tests_in_parallel' 
c:/Ruby193/lib/ruby/gems/1.9.1/gems/parallel_tests-0.15.0/lib/parallel_tests/cli 
.rb:25:in `block (2 levels) in execute_in_parallel' 
c:/Ruby193/lib/ruby/gems/1.9.1/gems/parallel-0.8.3/lib/parallel.rb:348:in`call'

c:/Ruby193/lib/ruby/gems/1.9.1/gems/parallel-0.8.3/lib/parallel.rb:348:in `call_ 
with_index' 
c:/Ruby193/lib/ruby/gems/1.9.1/gems/parallel-0.8.3/lib/parallel.rb:188:in`block 
(3 levels) in work_in_threads' 
c:/Ruby193/lib/ruby/gems/1.9.1/gems/parallel-0.8.3/lib/parallel.rb:356:in `with_ 
instrumentation' 
c:/Ruby193/lib/ruby/gems/1.9.1/gems/parallel-0.8.3/lib/parallel.rb:186:in`block 
(2 levels) in work_in_threads' 
c:/Ruby193/lib/ruby/gems/1.9.1/gems/parallel-0.8.3/lib/parallel.rb:180:in `loop'

c:/Ruby193/lib/ruby/gems/1.9.1/gems/parallel-0.8.3/lib/parallel.rb:180:in `block 
in work_in_threads' 
c:/Ruby193/lib/ruby/gems/1.9.1/gems/parallel-0.8.3/lib/parallel.rb:65:in`block 
(2 levels) in in_threads' 
c:/Ruby193/lib/ruby/1.9.1/win32ole.rb:13:in `call' 
c:/Ruby193/lib/ruby/1.9.1/win32ole.rb:13:in`block in initialize' 
Tasks: TOP => sauce:spec

Any idea?

**Comment by DylanLacey** [comment]
I think this issue may happen with older versions of the parallel_tests gem;  If you update to the latest version of the Sauce gem, does this still occur?
