### ISSUE TITLE
Upgrade from 3.1.1 to 3.5.3 results in Capybara::ElementNotFound errors

### ISSUE THREAD

**Issue by chrisvfritz** [saucelabs/sauce_ruby#279]
I recently upgraded a Rails 4.1.8 app from sauce 3.1.1 to 3.5.3. All specs were working with 3.1.1, but now I'm getting `Capybara::ElementNotFound` errors on every spec that uses sauce (both locally and on Travis CI). I'm using rspec 3.1.0, capybara 2.4.4, and in my `spec/rails_helper.rb`, I've set `Capybara.javascript_driver = :sauce`.

Any ideas what went wrong? I didn't have any problems using 3.1.1 and have just reverted back to it for now, but I like to keep my dependencies up to date.

**Comment by DylanLacey** [comment]
Ack!  Sorry, keeping up with issues hasn't been going so well.

That's a very odd result.  When you checked out the job on Sauce Labs, did it look like everything had loaded correctly?

**Comment by chrisvfritz** [comment]
Sorry, I don't have access to those logs anymore and this particular application ended up switching from sauce to just poltergeist for an unrelated reason: to give up more complete testing in exchange for speed as the project grew. 

Since I don't have any more information and no one else has chimed in with a, "Me too!" since November, I'll just close this issue.
