### ISSUE TITLE
Connection timeout on Travis since version 3.5.1

### ISSUE THREAD

**Issue by kostia** [saucelabs/sauce_ruby#290]
Hello,

since upgrade to `sauce-connect` 3.5.1, the gem is not able to create a connection on Travis CI. With version 3.5.0 everything is ok, but with the current version we're getting "Could not connect to Saucelabs...". Any ideas?

Kind regards
Kostia

**Comment by DylanLacey** [comment]
This is only happening with 3.5.1, earlier versions are still working?

**Comment by kostia** [comment]
Yes, the earlier versions are still working. Unfortunately I haven't yet tried the latest 3.5.2 version.

**Comment by DylanLacey** [comment]
Hmm.  We're deprecating older versions of SC (eg SC3) which are unfortunately still bundled with the gem, but updating to newer gems shouldn't cause issues.

Can you link me to a publically available Travis build, if you have one?

**Comment by kostia** [comment]
There is no public build, because we use the premium service. I will try the new version next week. I'm closing the issue, since I suppose that the upgrade will resolve the issue. If not - I will reopen it.

Thanks a lot for the support!

**Comment by DylanLacey** [comment]
Sure thing.  It's undocumented ATM, but if you want to switch to SC4 it's relatively easy, with the caveat you have to put the Sauce Connect in place yourself.  It's a partial solution for now, but we don't have an ETA on a better one -_-

You could also switch to the Travis integration: http://docs.travis-ci.com/user/sauce-connect/
