### ISSUE TITLE
Please update to parallel_tests 1.3.7

### ISSUE THREAD

**Issue by dankohn** [saucelabs/sauce_ruby#292]
We use parallel_tests all day and sauce occasionally. We'd like to get the most up-to-date parallel_tests but we're unable to while supporting sauce. Thanks.

**Comment by DylanLacey** [comment]
Sure thing, I'll update the gem ASAP.

**Comment by DylanLacey** [comment]
Having some problems with sudden total test explosions;  Apologies that this is taking longer then expected.

**Comment by dankohn** [comment]
That's cool, but thanks for looking into it.

**Comment by DylanLacey** [comment]
OK!  Took a while to fix, but can you give 3.5.5 a look?

**Comment by DylanLacey** [comment]
Closing this out.
