### ISSUE TITLE
Where is the sauce connect repo?

### ISSUE THREAD

**Issue by bootstraponline** [saucelabs/sauce_ruby#309]
The sauce connect gem on [rubygems](https://rubygems.org/gems/sauce-connect) says it's apache licensed however I don't see the repo linked anywhere. Is the sauce connect gem repo on GitHub?

**Comment by bootstraponline** [comment]
I'm not sure why there are multiple gems within the repo. I found [sauce connect](https://github.com/saucelabs/sauce_ruby/tree/master/gems/sauce-connect) in the gems folder.

**Comment by DylanLacey** [comment]
Basically, I inherited it like this.  Pulling the gems into their own repos is on the todo list, but I don't get as much time for the gem as I'd like currently.
