### ISSUE TITLE
Don't send invalid caps

### ISSUE THREAD

**Issue by bootstraponline** [saucelabs/sauce_ruby#326]
Sauce doesn't have uniform support for all their capabilities across all combinations. There appears to be no way in sauce_ruby to define a capability that applies only to a certain browser combination.

In my test I'm setting the screen resolution as follows:

```ruby
  config['screen-resolution']         = '1280x1024'
```

I then define the browsers to run on:

```ruby
  config[:browsers]                   = [
    ['Windows 8.1', 'Firefox', '37'],
    ['Windows 8.1', 'Chrome', '42'],
    ['OS X 10.10', 'Safari', '8.0']
]
```

Do you see the problem? OS X will immediately fail because it doesn't support resolution changes.

> Resolution you specified is not available for this OS/browser/version/device combo: OS: 'Mac 10.10', Browser: 'safari', Version: '8.0.', Device: 'unspecified', Screen Resolution: '1280x1024' available resolutions: '1024x768'

I'll figure out how to solve this in my fork however it'd be nice to have this resolved properly in the official gem.

**Comment by DylanLacey** [comment]
You can send individual capabilities by adding a hash to a browser array as the last parameter, eg

```ruby
Sauce.config do |c|
  c[:browsers] = [
    ["Windows 7", "Chrome", 38, {:screen_resolution => '1024 x 768'}]
    ["Windows 8", "Chrome", 38]
  ]
end

**Comment by bootstraponline** [comment]
Ok, that sounds good. I think the issue is still relevant, just less important. I don't want to duplicate the screen resolution for every browser. The sauce gem already whitelists the caps, it should not send combinations that don't make sense. You can see the change I made to the forked version of the gem linked earlier in this issue.

**Comment by bootstraponline** [comment]
https://github.com/saucelabs/sauce_ruby/issues/325 is probably better for tracking the client side validation effort.

**Comment by bootstraponline** [comment]
> Can you think of a better way to make this capability more obvious?  If it's tripped you up it's almost certainly tripping others.

I would expand upon the example to demonstrate multiple capabilities and add a comment in the code example. 

```

Sauce.config do |c|
  c.browsers = [
    ["Windows 7", "Firefox", "18"],
    # chrome specific desired capabilities
    ["Windows 7", "Chrome", 30, {:build => 'ChromeTastic', :'screen-resolution' => '1280x1024'}]
  ]
```

I'd rather the caps that apply to all browsers (ex: screen res) ignore bogus combinations so end users don't have to duplicate lots and lots of options for testing on many browsers.
