### ISSUE TITLE
Running ruby sauce tests using manually started tunnel?

### ISSUE THREAD

**Issue by lanceblais** [saucelabs/sauce_ruby#347]
Hello,

Is it possible to start up a tunnel manually via command line and have the sauce gem use that, or are we bound to setting the `:sauce_connect_4_executable` option in the `sauce_helper.rb` ?

Reason I ask is, we're having issues running it on CircleCI and their recommendation is to establish the tunnel first, then once it's up, run our tests.

**Comment by DylanLacey** [comment]
Absolutely.  You can just tell the gem to not try to start a tunnel:

```
Sauce.config do |c|
  c[:start_tunnel] = false
end
```

Assuming you're not using tunnel identifiers, your tests will automatically use a tunnel started with the same credentials.
